version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_URL: "${DB_URL}"  # Connect to the db service
      HTTP_PORT: ${HTTP_PORT}
      GATEWAY_A_URL: "${GATEWAY_A_URL}"  
      GATEWAY_B_URL: "${GATEWAY_B_URL}"  
      TIMEOUT: "${TIMEOUT}"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: "test_work"
      POSTGRES_USER: "dunsinolubobokun"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
